all:
	make --directory=backtracking
	make --directory=greedy
	make --directory=local
	make --directory=grasp

clean:
	make clean --directory=backtracking
	make clean --directory=greedy
	make clean --directory=local
	make clean --directory=grasp